name: CheckOut Subfoler and run script

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: ChecOut Repo
        uses: actions/checkout@v4
        with:
          sparse-checkout-cone-mode: 'false'
          sparse-checkout: |
            testsub1/testsub2/
          path: .

      - name: List files and CHMOD
        run: |
          pwd
          ls -la
          cd testsub1/testsub2
          chmod +x ./script.sh

      - name: Run script
        run: |
          cd testsub1/testsub2
          ./script.sh